name: Java CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
          
      - name: Permission
        run: chmod 777 /pl/put/poznan/io-project-architecture/0.1/io-project-architecture-0.1.jar
        
      - name: Validate, build and run tests
        run: mvn validate compile test package verify install deploy
