name: Build JAR, Generate javadoc and release
on: 
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build jar
        run: mvn -B package --file pom.xml
      - name: Generate javadoc
        run: mvn javadoc:javadoc
      - name: Create zip with doc
        run: zip -r ./target/docs.zip ./target/apidocs
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "target/docs.zip,target/io-project-architecture-0.1.jar"
          token: ${{ secrets.GITHUB_TOKEN }}
