name: Build JAR, Generate javadoc and release
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build jar
        run: mvn -B package --file pom.xml
      - name: Generate javadoc
        run: mvn javadoc:javadoc
      - name: Show files after
        run: ls target -R
