name: Build JAR, Generate javadoc and release
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/checkout@v2
      #- name: Set up JDK 11
      #  uses: actions/setup-java@v2
      #  with:
      #    java-version: '11'
      #    distribution: 'adopt'
      #    cache: maven
      - name: Show files before
        run: ls
      - name: Build jar
        run: ls
      - name: Generate javadoc
        run: ls
      - name: Show files after
        run: ls
